//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusInfo_Assignment3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBusInfo
    {
        public int BusID { get; set; }
        public string BoardPoint { get; set; }
        public string TravelDate { get; set; }
        public decimal Amount { get; set; }
        public int Rating { get; set; }
    }
}
